### ISSUE TITLE
browserSync

### ISSUE THREAD

**Issue by chrisdubya** [niceandserious/crafty-vagrant#12]
I've forked the repo and am trying to add browserSync to the gulpfile, mainly for scss and script update.  

Just wanted to know if you have already been working on this feature yet?  

Eventually it would be nice to also get it working with .html.  I had it working on the PwC EYF, but was using nunjucks for the templating.

**Comment by nickautomatic** [comment]
Hey Chris! I haven't tried browserSync with Craft yet, but as it happens I did recently set it up on my personal front-end boilerplate repo. That's not currently on the public web anywhere, but the Gulpfile is basically lifted from Crafty Vagrant, to which I added the following task:

```javascript
/**
 * $ gulp serve
 *
 * - serve contents of public via BrowserSync
 * - watch for updates
 */
gulp.task('serve', ['watch'], function() {
  // Serve contents of destination directory via BrowserSync:
  plugins.browserSync.init({
      server: {
          baseDir: path.dest
      }
  });

  // When anything changes in the public directory, reload:
  gulp.watch([
    path.dest + '/**/*.*'
  ])
  .on('change', plugins.browserSync.reload);
});
```

...you'll also need to add `'browser-sync'` to the Load plugins patterns at the top of the Gulpfile (and of course `npm install` it). Hopefully that should do it. I set that up pretty quickly a little while ago and I've found it sometimes behaves slightly quirkily (trouble getting it to quit sometimes), so would definitely be interested to know how it works out for you.

**Comment by peterlarkin** [comment]
Is this for a Craft project @chrisdubya? 

I tried out grunt-contrib-watch (which has livereload built in) with Crafty Vagrant a while back and did get it to work. I had to manually add the livereload script to the _layout.twig template, but only for devMode like so:

```
{% if craft.config.devMode %}
    <!-- script here -->
{% endif %}
```

You can also add .twig / .html files to the watch task and it'll refresh when you change them. Although I don't know how this would work with a gulp / browsersync set up!

**Comment by chrisdubya** [comment]
@peterlarkin Yeah, I'm to give it a go tonight.  I also want to try to switch from Vagrant to Docker, for whenever Craft decides to add postgres, nosql support.

'Crafty Docker'?  Sounds like a dirty movie.

**Comment by nickautomatic** [comment]
@chrisdubya Ha, funnily enough I was playing around with Docker a few days ago, thinking exactly the same thing. Although more for speed reasons than anything else (it seems containers are a lot faster than a full VM). Let us know if you get anywhere with it - I'll definitely be interested!

**Comment by chrisdubya** [comment]
@nickautomatic Yeah, it caches builds really well.  And I found a way on docker compose to mount volumes on your db container, so you can run a vm with or without persisted data.  Tres tres exciting.

**Comment by chrisdubya** [comment]
@nickautomatic I've hit a wall with the browsersync.  If you checkout the gulpfile on the fork and have any ideas, that would be amazing.  Think it might have something to do with the 'path.dest' git@github.com:chrisdubya/crafty-vagrant.git

**Comment by nickautomatic** [comment]
@chrisdubya Ah, right. I forgot that with the site needs to be served via Apache, PHP, etc, rather than directly via Node.js / Browsersync. You can do that using Browsersync's `proxy` option (instead of `server`). So the task would look something like this:

```javascript
gulp.task('serve', ['watch'], function() {
  // Serve contents of destination directory via BrowserSync:
  plugins.browserSync.init({
    proxy: 'craft.dev'
  });

  // When anything changes in the public directory, reload:
  gulp.watch([
    path.src + '/**/*.*',
    './app/craft/templates/**/*.twig'
  ])
  .on('change', plugins.browserSync.reload);
});
```
...I also hadn't taken into account that (as @peterlarkin pointed out) the templates need to be watched separately too, so I've added that.

Just realised that this set up will (I think) do a full page reload on every change, which might not be the most efficient approach (it's probably possible to set it up more cleverly so that, eg. CSS files get autoupdated/injected without a full page refresh), but should at least work...

**Comment by nickautomatic** [comment]
Hey @chrisdubya, thanks for that. I've done this as a separate commit to avoid pulling the extra stuff that was in the pull request. The difference between the version I've pushed and your version is that I've left notifications on for Crafty Vagrant, and I've also added a line in the styles task to make sure styles always get injected without a page refresh (changes to templates and scripts cause a full page reload). Anyway, thanks again - this was a really good suggestion.

**Comment by chrisdubya** [comment]
Hey @nickautomatic, I just updated the comments on the post install message shell script and pushed it up.  I probably should have put it on a separate branch and did a PR but I forgot.  Oh, well...

Tested it out and works great!

**Comment by peterlarkin** [comment]
@nickautomatic @chrisdubya 

I've been incorporating this into my project tonight and have made a few improvements to the browsersync setup. I've created a pull request (#15). Would be great to see what you guys think – it's working really well for me. Changes include:

- You can now serve over your vhost URL (http://craft.dev) and still get livereloading, rather than browsersync opening up http://localhost:3000 and only livereloading there. This requires a script tag in the _layout template (but only in craft.config.devMode).
- Only do a full page refresh for changes to twig templates. Styles *and* now scripts are now both streamed and injected on change.
- I've changed the task to `gulp serve` as it feels more natural and is a bit quicker than `gulp browsersync` :smile:

**Comment by chrisdubya** [comment]
@peterlarkin @nickautomatic I think that makes more sense, especially the `gulp serve`, `gulp browsersync` isn't really a commonly known way of serving.

I understand why you would want to separate watch and browsersync, but I think defaulting to `gulp serve` to have browsersync makes more sense, that's the expected behavior in the generator-webapp in yeoman.

Only issue I see, is what if I have multiple vhosts, because for some reason I run a lot of virtual boxes(I don't)?  But I could see that being an issue.

**Comment by peterlarkin** [comment]
Yeah, I guess the ideal situation (my opinion) would be to have to have `gulp serve` be the default and then have a `gulp serve --no-livereload` flag just execute the `gulp watch` task without browsersync.

Not sure about the multiple vhosts. On starting a project, I normally change it from craft.dev to whatever the name of the project I'm working on is (e.g. niceandserious.dev) and this only applies in the project's vagrant environment (and your hosts file setup). If it was required, you could maybe set it up to pass in the serverName variable with a flag?

**Comment by nickautomatic** [comment]
@peterlarkin @chrisdubya 

This all sounds really cool. Nice work getting it working with the custom domain, in particular. Also I like that you've stopped it auto-opening a browser tab - that's always slightly bugged me slightly. Didn't realise you could turn it off!

Script injecting sounds cool too. I left that out yesterday just because I wasn't sure what happens to, eg. listeners / document onload scripts, etc, and didn't have time to test properly.

Re: `gulp serve` - ha, that's interesting. I renamed it to `browsersync` when I switched it to a proxy, because it seemed to me potentially misleading (especially to anyone less familiar with Vagrant) to still call it `serve` - which to me implies Browsersync is firing up an Express server. I felt this could lead you to reason wrongly about how the system works (since now Vagrant is really the server, and Browsersync is just acting as a proxy / middleware). I chose `browsersync` because Browsersync is also a command line tool, so `gulp browsersync` seemed like the logical command for calling it through Gulp... Totally agree that it's not the catchiest task name, though!

However! I really like your idea of using a `--no-livereload` flag. I'd be inclined to just make Browsersync the default `gulp watch` task, and then have a `gulp watch --no-livereload` option. Especially if Browsersync doesn't auto-open a new tab, the current task feels like an enhanced, slightly magical drop-in replacement for `gulp watch`

@peterlarkin - I've pulled in your changes, and I'll have a go at getting that `--no-livereload` thing to work before I merge them in to master, if that's ok with you. I'd also like to sort out an issue that seems to be happening with port forwarding on Windows 10...

@chrisdubya - re: Docker, you might be interested in [this](https://blog.docker.com/2016/03/docker-for-mac-windows-beta/) - they just announced native Docker on OSX / Windows, instead of having to always run it through a Linux VM.

**Comment by chrisdubya** [comment]
@nickautomatic yeah that's pretty much how we're using it for the product I'm working on right now. And we're just waiting for the Windows support to get stable. 

We're running Ubuntu:alpine which is like 26mb and gets cached, and is enough to run node and Postgres, so running the containers is so fast. I found this https://github.com/gabrielmoreira/craftman, but I'm currently working through an issue with them with OSX. But maybe it will be a good starting point for migrating from Vagrant.

**Comment by chrisdubya** [comment]
@nickautomatic @peterlarkin re:gulp I get the 'serve' thing cause it's not really the server. But what if you just made it the default 'gulp' task. Then add the flags for watch or no reload to that?

**Comment by nickautomatic** [comment]
Tbh, I think as it's now configured, Browsersync just adds a nice extra bit of functionality to `gulp watch`. I can't see much of a downside, especially if it's not auto-opening tabs, so I've tweaked the Gulpfile to do just that. There's a way of calling `gulp watch` without Browsersync if you want to, but Browsersync works really well so I'm totally happy to have it as the default watch behaviour.

(If you want to watch without Browsersync, you can use `gulp watch:tasks` to just run the watch tasks directly. It might not seem as logical as `gulp watch --no-livereload` from a command line perspective, but it keeps the Gulpfile cleaner, simpler and more readable than that approach would, which I think is more important, given that the intention is that there shouldn't really be any need to do that)

**Comment by peterlarkin** [comment]
Nice one. I did think about `gulp serve` being slightly different in this context after committing. I'm happy to stick with `gulp watch` with BrowserSync default!
